### ISSUE TITLE
oracle.eclipselink.coherence.integrated.internal.cache.LockVersionExtractor 找不到

### ISSUE THREAD

**Issue by changmaoLi** [rufherg/WebLogic_Basic_Poc#2]
你好， 这个类我找了很久找不到相应的jar。 请问在哪儿可以找到？

**Comment by rufherg** [comment]
![image](https://user-images.githubusercontent.com/37505703/98531998-11a2a580-22bc-11eb-9332-09452a17397a.png)
![image](https://user-images.githubusercontent.com/37505703/98532025-19fae080-22bc-11eb-9763-64ac68a07162.png)
你去weblogic的目录下搜索这个jar包，可能会有重名的，这个自己区别一下~

**Comment by Schira4396** [comment]
> 你好，这个类我找了很久以前相应的罐子。请问在哪儿可以找到？

你找到了没？我一直找不到

**Comment by rufherg** [comment]
> > 你好，这个类我找了很久以前相应的罐子。请问在哪儿可以找到？
> 
> 你找到了没？我一直找不到

三个类对应的jar包已经打包好了，对于weblogic 12.2.1.4.0版本
[libs.zip](https://github.com/rufherg/WebLogic_Basic_Poc/files/5812831/libs.zip)
